export const WORLD_COUNTRIES = [
  { name: "Afghanistan", code: "AF", region: "Asia", port: "" },
  { name: "Albania", code: "AL", region: "Europe", port: "" },
  { name: "Algeria", code: "DZ", region: "Africa", port: "Port of Algiers / Port of Oran" },
  { name: "Andorra", code: "AD", region: "Europe", port: "" },
  { name: "Angola", code: "AO", region: "Africa", port: "Port of Luanda" },
  { name: "Antigua and Barbuda", code: "AG", region: "Caribbean", port: "" },
  { name: "Argentina", code: "AR", region: "South America", port: "Port of Buenos Aires / Port of Rosario" },
  { name: "Armenia", code: "AM", region: "Asia", port: "" },
  { name: "Australia", code: "AU", region: "Oceania", port: "Port of Melbourne / Port of Sydney / Port Botany" },
  { name: "Austria", code: "AT", region: "Europe", port: "" },
  { name: "Azerbaijan", code: "AZ", region: "Asia", port: "Port of Baku" },
  { name: "Bahamas", code: "BS", region: "Caribbean", port: "Port of Nassau" },
  { name: "Bahrain", code: "BH", region: "Middle East", port: "Khalifa Bin Salman Port" },
  { name: "Bangladesh", code: "BD", region: "Asia", port: "Port of Chittagong / Mongla Port" },
  { name: "Barbados", code: "BB", region: "Caribbean", port: "Bridgetown Port" },
  { name: "Belarus", code: "BY", region: "Europe", port: "" },
  { name: "Belgium", code: "BE", region: "Europe", port: "Port of Antwerp / Port of Zeebrugge" },
  { name: "Belize", code: "BZ", region: "Central America", port: "Port of Belize City" },
  { name: "Benin", code: "BJ", region: "Africa", port: "Port of Cotonou" },
  { name: "Bhutan", code: "BT", region: "Asia", port: "" },
  { name: "Bolivia", code: "BO", region: "South America", port: "" },
  { name: "Bosnia and Herzegovina", code: "BA", region: "Europe", port: "Port of Ploče" },
  { name: "Botswana", code: "BW", region: "Africa", port: "" },
  { name: "Brazil", code: "BR", region: "South America", port: "Port of Santos / Port of Paranaguá" },
  { name: "Brunei", code: "BN", region: "Asia", port: "Port of Muara" },
  { name: "Bulgaria", code: "BG", region: "Europe", port: "Port of Varna / Port of Burgas" },
  { name: "Burkina Faso", code: "BF", region: "Africa", port: "" },
  { name: "Burundi", code: "BI", region: "Africa", port: "" },
  { name: "Cambodia", code: "KH", region: "Asia", port: "Port of Sihanoukville" },
  { name: "Cameroon", code: "CM", region: "Africa", port: "Port of Douala" },
  { name: "Canada", code: "CA", region: "North America", port: "Port of Vancouver / Port of Montreal / Port of Halifax" },
  { name: "Cape Verde", code: "CV", region: "Africa", port: "Port of Praia" },
  { name: "Central African Republic", code: "CF", region: "Africa", port: "" },
  { name: "Chad", code: "TD", region: "Africa", port: "" },
  { name: "Chile", code: "CL", region: "South America", port: "Port of Valparaíso / Port of San Antonio / Port of Antofagasta" },
  { name: "China", code: "CN", region: "Asia", port: "Port of Shanghai / Port of Tianjin / Port of Ningbo" },
  { name: "Colombia", code: "CO", region: "South America", port: "Port of Cartagena / Port of Buenaventura / Port of Barranquilla" },
  { name: "Comoros", code: "KM", region: "Africa", port: "" },
  { name: "Congo (Democratic Republic)", code: "CD", region: "Africa", port: "Port of Matadi" },
  { name: "Congo (Republic)", code: "CG", region: "Africa", port: "Port of Pointe-Noire" },
  { name: "Costa Rica", code: "CR", region: "Central America", port: "Port of Limón / Port of Caldera" },
  { name: "Croatia", code: "HR", region: "Europe", port: "Port of Rijeka / Port of Split" },
  { name: "Cuba", code: "CU", region: "Caribbean", port: "Port of Havana / Port of Mariel" },
  { name: "Cyprus", code: "CY", region: "Europe", port: "Port of Limassol" },
  { name: "Czech Republic", code: "CZ", region: "Europe", port: "" },
  { name: "Denmark", code: "DK", region: "Europe", port: "Port of Copenhagen / Port of Aarhus" },
  { name: "Djibouti", code: "DJ", region: "Africa", port: "Port of Djibouti" },
  { name: "Dominican Republic", code: "DO", region: "Caribbean", port: "Port of Santo Domingo / Port of Caucedo" },
  { name: "Ecuador", code: "EC", region: "South America", port: "Port of Guayaquil / Port of Manta" },
  { name: "Egypt", code: "EG", region: "Middle East", port: "Port of Alexandria / Port Said / Port of Damietta" },
  { name: "El Salvador", code: "SV", region: "Central America", port: "Port of Acajutla" },
  { name: "Equatorial Guinea", code: "GQ", region: "Africa", port: "Port of Malabo / Port of Bata" },
  { name: "Eritrea", code: "ER", region: "Africa", port: "Port of Massawa" },
  { name: "Estonia", code: "EE", region: "Europe", port: "Port of Tallinn" },
  { name: "Eswatini", code: "SZ", region: "Africa", port: "" },
  { name: "Ethiopia", code: "ET", region: "Africa", port: "" },
  { name: "Fiji", code: "FJ", region: "Oceania", port: "Port of Suva" },
  { name: "Finland", code: "FI", region: "Europe", port: "Port of Helsinki / Port of HaminaKotka" },
  { name: "France", code: "FR", region: "Europe", port: "Port of Marseille / Port of Le Havre / Port of Dunkirk" },
  { name: "Gabon", code: "GA", region: "Africa", port: "Port of Libreville / Port of Owendo" },
  { name: "Gambia", code: "GM", region: "Africa", port: "Port of Banjul" },
  { name: "Georgia", code: "GE", region: "Asia", port: "Port of Batumi / Port of Poti" },
  { name: "Germany", code: "DE", region: "Europe", port: "Port of Hamburg / Port of Bremen / Port of Bremerhaven" },
  { name: "Ghana", code: "GH", region: "Africa", port: "Port of Tema / Port of Takoradi" },
  { name: "Greece", code: "GR", region: "Europe", port: "Port of Piraeus / Port of Thessaloniki" },
  { name: "Guatemala", code: "GT", region: "Central America", port: "Port of Puerto Quetzal / Port of Santo Tomás de Castilla" },
  { name: "Guinea", code: "GN", region: "Africa", port: "Port of Conakry" },
  { name: "Guinea-Bissau", code: "GW", region: "Africa", port: "Port of Bissau" },
  { name: "Guyana", code: "GY", region: "South America", port: "Port of Georgetown" },
  { name: "Haiti", code: "HT", region: "Caribbean", port: "Port of Port-au-Prince" },
  { name: "Honduras", code: "HN", region: "Central America", port: "Port of Puerto Cortés / Port of La Ceiba" },
  { name: "Hungary", code: "HU", region: "Europe", port: "" },
  { name: "Iceland", code: "IS", region: "Europe", port: "Port of Reykjavík" },
  { name: "India", code: "IN", region: "Asia", port: "Jawaharlal Nehru Port (JNPT) / Port of Mumbai / Port of Chennai" },
  { name: "Indonesia", code: "ID", region: "Asia", port: "Port of Tanjung Priok (Jakarta) / Port of Belawan / Port of Surabaya" },
  { name: "Iran", code: "IR", region: "Middle East", port: "Port of Bandar Abbas / Port of Imam Khomeini" },
  { name: "Iraq", code: "IQ", region: "Middle East", port: "Port of Umm Qasr / Port of Basra" },
  { name: "Ireland", code: "IE", region: "Europe", port: "Port of Dublin / Port of Cork" },
  { name: "Israel", code: "IL", region: "Middle East", port: "Port of Haifa / Port of Ashdod" },
  { name: "Italy", code: "IT", region: "Europe", port: "Port of Genoa / Port of Gioia Tauro / Port of La Spezia / Port of Naples" },
  { name: "Ivory Coast", code: "CI", region: "Africa", port: "Port of Abidjan / Port of San Pédro" },
  { name: "Jamaica", code: "JM", region: "Caribbean", port: "Port of Kingston / Port of Montego Bay" },
  { name: "Japan", code: "JP", region: "Asia", port: "Port of Tokyo / Port of Yokohama / Port of Nagoya / Port of Osaka" },
  { name: "Jordan", code: "JO", region: "Middle East", port: "Port of Aqaba" },
  { name: "Kazakhstan", code: "KZ", region: "Asia", port: "Port of Aktau" },
  { name: "Kenya", code: "KE", region: "Africa", port: "Port of Mombasa" },
  { name: "Kiribati", code: "KI", region: "Oceania", port: "" },
  { name: "Kuwait", code: "KW", region: "Middle East", port: "Port of Shuwaikh / Port of Shuaiba" },
  { name: "Kyrgyzstan", code: "KG", region: "Asia", port: "" },
  { name: "Laos", code: "LA", region: "Asia", port: "" },
  { name: "Latvia", code: "LV", region: "Europe", port: "Port of Riga / Port of Ventspils" },
  { name: "Lebanon", code: "LB", region: "Middle East", port: "Port of Beirut / Port of Tripoli" },
  { name: "Lesotho", code: "LS", region: "Africa", port: "" },
  { name: "Liberia", code: "LR", region: "Africa", port: "Port of Monrovia" },
  { name: "Libya", code: "LY", region: "Africa", port: "Port of Tripoli / Port of Benghazi / Port of Misrata" },
  { name: "Liechtenstein", code: "LI", region: "Europe", port: "" },
  { name: "Lithuania", code: "LT", region: "Europe", port: "Port of Klaipeda" },
  { name: "Luxembourg", code: "LU", region: "Europe", port: "" },
  { name: "Madagascar", code: "MG", region: "Africa", port: "Port of Toamasina" },
  { name: "Malawi", code: "MW", region: "Africa", port: "" },
  { name: "Malaysia", code: "MY", region: "Asia", port: "Port of Klang / Port of Penang / Port of Tanjung Pelepas" },
  { name: "Maldives", code: "MV", region: "Asia", port: "Port of Malé" },
  { name: "Mali", code: "ML", region: "Africa", port: "" },
  { name: "Malta", code: "MT", region: "Europe", port: "Port of Valletta / Marsaxlokk Port" },
  { name: "Marshall Islands", code: "MH", region: "Oceania", port: "" },
  { name: "Mauritania", code: "MR", region: "Africa", port: "Port of Nouakchott" },
  { name: "Mauritius", code: "MU", region: "Africa", port: "Port Louis" },
  { name: "Mexico", code: "MX", region: "North America", port: "Port of Manzanillo / Port of Veracruz / Port of Altamira" },
  { name: "Micronesia", code: "FM", region: "Oceania", port: "" },
  { name: "Moldova", code: "MD", region: "Europe", port: "" },
  { name: "Monaco", code: "MC", region: "Europe", port: "" },
  { name: "Mongolia", code: "MN", region: "Asia", port: "" },
  { name: "Montenegro", code: "ME", region: "Europe", port: "Port of Bar" },
  { name: "Morocco", code: "MA", region: "Africa", port: "Port of Casablanca / Port of Tanger Med / Port of Agadir" },
  { name: "Mozambique", code: "MZ", region: "Africa", port: "Port of Maputo / Port of Beira" },
  { name: "Myanmar", code: "MM", region: "Asia", port: "Port of Yangon / Port of Thilawa" },
  { name: "Namibia", code: "NA", region: "Africa", port: "Port of Walvis Bay" },
  { name: "Nauru", code: "NR", region: "Oceania", port: "" },
  { name: "Nepal", code: "NP", region: "Asia", port: "" },
  { name: "Netherlands", code: "NL", region: "Europe", port: "Port of Rotterdam / Port of Amsterdam" },
  { name: "New Zealand", code: "NZ", region: "Oceania", port: "Port of Auckland / Port of Tauranga" },
  { name: "Nicaragua", code: "NI", region: "Central America", port: "Port of Corinto / Port of Puerto Cabezas" },
  { name: "Niger", code: "NE", region: "Africa", port: "" },
  { name: "Nigeria", code: "NG", region: "Africa", port: "Port of Lagos (Apapa) / Port of Tin Can Island / Port of Onne" },
  { name: "North Korea", code: "KP", region: "Asia", port: "" },
  { name: "North Macedonia", code: "MK", region: "Europe", port: "" },
  { name: "Norway", code: "NO", region: "Europe", port: "Port of Oslo / Port of Bergen / Port of Stavanger" },
  { name: "Oman", code: "OM", region: "Middle East", port: "Port of Salalah / Port of Sohar / Port of Muscat" },
  { name: "Pakistan", code: "PK", region: "Asia", port: "Port of Karachi / Port of Qasim" },
  { name: "Palau", code: "PW", region: "Oceania", port: "" },
  { name: "Palestine", code: "PS", region: "Middle East", port: "" },
  { name: "Panama", code: "PA", region: "Central America", port: "Port of Balboa / Port of Cristóbal / Port of Manzanillo" },
  { name: "Papua New Guinea", code: "PG", region: "Oceania", port: "Port of Port Moresby / Port of Lae" },
  { name: "Paraguay", code: "PY", region: "South America", port: "Port of Asunción / Port of Villeta" },
  { name: "Peru", code: "PE", region: "South America", port: "Port of Callao / Port of Paita / Port of Ilo" },
  { name: "Philippines", code: "PH", region: "Asia", port: "Port of Manila / Port of Cebu / Port of Davao" },
  { name: "Poland", code: "PL", region: "Europe", port: "Port of Gdańsk / Port of Gdynia / Port of Szczecin" },
  { name: "Portugal", code: "PT", region: "Europe", port: "Port of Lisbon / Port of Sines / Port of Leixões" },
  { name: "Qatar", code: "QA", region: "Middle East", port: "Port of Hamad / Port of Doha" },
  { name: "Romania", code: "RO", region: "Europe", port: "Port of Constanța" },
  { name: "Russia", code: "RU", region: "Europe", port: "Port of St. Petersburg / Port of Novorossiysk / Port of Vladivostok" },
  { name: "Rwanda", code: "RW", region: "Africa", port: "" },
  { name: "Saint Kitts and Nevis", code: "KN", region: "Caribbean", port: "" },
  { name: "Saint Lucia", code: "LC", region: "Caribbean", port: "Port of Castries" },
  { name: "Saint Vincent and the Grenadines", code: "VC", region: "Caribbean", port: "" },
  { name: "Samoa", code: "WS", region: "Oceania", port: "Port of Apia" },
  { name: "San Marino", code: "SM", region: "Europe", port: "" },
  { name: "São Tomé and Príncipe", code: "ST", region: "Africa", port: "" },
  { name: "Saudi Arabia", code: "SA", region: "Middle East", port: "Port of Jeddah / King Abdulaziz Port (Dammam) / Jubail Commercial Port" },
  { name: "Senegal", code: "SN", region: "Africa", port: "Port of Dakar" },
  { name: "Serbia", code: "RS", region: "Europe", port: "" },
  { name: "Seychelles", code: "SC", region: "Africa", port: "Port of Victoria" },
  { name: "Sierra Leone", code: "SL", region: "Africa", port: "Port of Freetown" },
  { name: "Singapore", code: "SG", region: "Asia", port: "Port of Singapore" },
  { name: "Slovakia", code: "SK", region: "Europe", port: "" },
  { name: "Slovenia", code: "SI", region: "Europe", port: "Port of Koper" },
  { name: "Solomon Islands", code: "SB", region: "Oceania", port: "Port of Honiara" },
  { name: "Somalia", code: "SO", region: "Africa", port: "Port of Mogadishu / Port of Berbera" },
  { name: "South Africa", code: "ZA", region: "Africa", port: "Port of Durban / Port of Cape Town / Port of Port Elizabeth" },
  { name: "South Korea", code: "KR", region: "Asia", port: "Port of Busan / Port of Incheon / Port of Gwangyang" },
  { name: "South Sudan", code: "SS", region: "Africa", port: "" },
  { name: "Spain", code: "ES", region: "Europe", port: "Port of Algeciras / Port of Barcelona / Port of Valencia" },
  { name: "Sri Lanka", code: "LK", region: "Asia", port: "Port of Colombo / Port of Hambantota" },
  { name: "Sudan", code: "SD", region: "Africa", port: "Port of Port Sudan" },
  { name: "Suriname", code: "SR", region: "South America", port: "Port of Paramaribo" },
  { name: "Sweden", code: "SE", region: "Europe", port: "Port of Gothenburg / Port of Stockholm" },
  { name: "Switzerland", code: "CH", region: "Europe", port: "" },
  { name: "Syria", code: "SY", region: "Middle East", port: "Port of Latakia / Port of Tartus" },
  { name: "Taiwan", code: "TW", region: "Asia", port: "Port of Kaohsiung / Port of Taipei / Port of Keelung" },
  { name: "Tajikistan", code: "TJ", region: "Asia", port: "" },
  { name: "Tanzania", code: "TZ", region: "Africa", port: "Port of Dar es Salaam / Port of Zanzibar" },
  { name: "Thailand", code: "TH", region: "Asia", port: "Port of Laem Chabang / Port of Bangkok" },
  { name: "Timor-Leste", code: "TL", region: "Asia", port: "Port of Dili" },
  { name: "Togo", code: "TG", region: "Africa", port: "Port of Lomé" },
  { name: "Tonga", code: "TO", region: "Oceania", port: "" },
  { name: "Trinidad and Tobago", code: "TT", region: "Caribbean", port: "Port of Port of Spain / Port of Point Lisas" },
  { name: "Tunisia", code: "TN", region: "Africa", port: "Port of Tunis-La Goulette / Port of Sfax / Port of Sousse" },
  { name: "Turkey", code: "TR", region: "Europe", port: "Port of Mersin / Port of Ambarli (Istanbul) / Port of Izmir / Port of Gemlik" },
  { name: "Turkmenistan", code: "TM", region: "Asia", port: "Port of Turkmenbashi" },
  { name: "Tuvalu", code: "TV", region: "Oceania", port: "" },
  { name: "Uganda", code: "UG", region: "Africa", port: "" },
  { name: "Ukraine", code: "UA", region: "Europe", port: "Port of Odessa / Port of Chornomorsk / Port of Mykolaiv" },
  { name: "United Arab Emirates", code: "AE", region: "Middle East", port: "Jebel Ali (Dubai) / Port of Abu Dhabi / Port of Sharjah" },
  { name: "United Kingdom", code: "GB", region: "Europe", port: "Port of Felixstowe / Port of Southampton / Port of London / Port of Liverpool" },
  { name: "United States", code: "US", region: "North America", port: "Port of Los Angeles / Port of Long Beach / Port of New York / Port of Houston" },
  { name: "Uruguay", code: "UY", region: "South America", port: "Port of Montevideo" },
  { name: "Uzbekistan", code: "UZ", region: "Asia", port: "" },
  { name: "Vanuatu", code: "VU", region: "Oceania", port: "Port of Port Vila" },
  { name: "Venezuela", code: "VE", region: "South America", port: "Port of La Guaira / Port of Puerto Cabello / Port of Maracaibo" },
  { name: "Vietnam", code: "VN", region: "Asia", port: "Port of Ho Chi Minh City / Port of Hai Phong / Port of Da Nang" },
  { name: "Yemen", code: "YE", region: "Middle East", port: "Port of Aden / Port of Hodeidah" },
  { name: "Zambia", code: "ZM", region: "Africa", port: "" },
  { name: "Zimbabwe", code: "ZW", region: "Africa", port: "" },
];

export function searchCountries(query) {
  if (!query || query.length < 1) return WORLD_COUNTRIES;
  const q = query.toLowerCase();
  return WORLD_COUNTRIES
    .filter(c => c.name.toLowerCase().includes(q))
    .sort((a, b) => {
      const aName = a.name.toLowerCase();
      const bName = b.name.toLowerCase();
      const aExact = aName === q;
      const bExact = bName === q;
      if (aExact && !bExact) return -1;
      if (!aExact && bExact) return 1;
      const aStart = aName.startsWith(q);
      const bStart = bName.startsWith(q);
      if (aStart && !bStart) return -1;
      if (!aStart && bStart) return 1;
      return a.name.localeCompare(b.name);
    });
}
